## MULTIPART (MultipartProperties)
# Enable multipart uploads
server:
    port : 8283
spring:
    jpa:
        hibernate:
            ddl-auto: create-drop
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        url: "jdbc:postgresql://localhost:5432/causea"
        username: postgres
        password: password123