## MULTIPART (MultipartProperties)
# Enable multipart uploads
server:
    port : 8283
spring:
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 215MB
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://igorski.eu.auth0.com/
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        url: "jdbc:postgresql://db:5432/causea"
        username: postgres
        password: password123
file:
    upload-dir: ./uploads

auth0:
    audience: https://buy-it-api.igorski.co
amazonProperties:
    endpointUrl: https://s3.eu-north-1.amazonaws.com
    downloadUrl: http://s3.eu-north-1.amazonaws.com
    accessKey: ${AWS_ACESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
    bucketName: buy-it-api