## MULTIPART (MultipartProperties)
auth0:
    audience: https://buy-it-api.igorski.co
    domain: igorski.eu.auth0.com
# Enable multipart uploads
spring:
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 215MB
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://${auth0.domain}/
file:
    upload-dir: ./uploads
amazonProperties:
    endpointUrl: https://s3.eu-north-1.amazonaws.com
    downloadUrl: http://s3.eu-north-1.amazonaws.com
    accessKey: ${AWS_ACESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
    bucketName: buy-it-api