## MULTIPART (MultipartProperties)
# Enable multipart uploads
server:
    port : 8080
spring:
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        url: ${CAUSEA_STAGING_DB_URL}
        username: ${CAUSEA_STAGING_DB_USER}
        password: ${CAUSEA_STAGING_DB_PASSWORD}